import { supabase } from './supabase.js'
import { applyRoleGuard } from './role-guard.js?v=3.12.0'
const $=id=>document.getElementById(id)
const el={backBtn:$('backBtn'),logoutBtn:$('logoutBtn'),branchText:$('branchText'),userName:$('userName'),dateFrom:$('dateFrom'),dateTo:$('dateTo'),loadReportBtn:$('loadReportBtn'),grossSales:$('grossSales'),totalDiscount:$('totalDiscount'),netSales:$('netSales'),cogs:$('cogs'),grossProfit:$('grossProfit'),grossMargin:$('grossMargin'),marketingDiscount:$('marketingDiscount'),manualDiscount:$('manualDiscount'),billCount:$('billCount'),profitAfterMarketing:$('profitAfterMarketing'),campaignCostList:$('campaignCostList'),pageMessage:$('pageMessage')}
const money=v=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',minimumFractionDigits:2}).format(Number(v||0))
const fmt=d=>{const p=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
function setRange(){const n=new Date(),s=new Date(n.getFullYear(),n.getMonth(),1);el.dateFrom.value=fmt(s);el.dateTo.value=fmt(n)}
async function loadSummary(){const{data,error}=await supabase.rpc('cost_control_summary',{p_date_from:el.dateFrom.value,p_date_to:el.dateTo.value});if(error)throw error;const r=Array.isArray(data)?data[0]:data;const net=Number(r?.net_sales||0),gp=Number(r?.gross_profit||0);el.grossSales.textContent=money(r?.gross_sales);el.totalDiscount.textContent=money(r?.total_discount);el.netSales.textContent=money(net);el.cogs.textContent=money(r?.cogs);el.grossProfit.textContent=money(gp);el.grossMargin.textContent=net>0?`${(gp/net*100).toFixed(2)}%`:'0.00%';el.marketingDiscount.textContent=money(r?.marketing_discount);el.manualDiscount.textContent=money(r?.manual_discount);el.billCount.textContent=Number(r?.bill_count||0).toLocaleString('th-TH');el.profitAfterMarketing.textContent=money(gp)}
async function loadCampaigns(){const{data,error}=await supabase.rpc('marketing_campaign_report');if(error)throw error;const a=Array.isArray(data)?data:[];el.campaignCostList.innerHTML=a.length?a.map(r=>{const b=Number(r.budget_amount||0),u=Number(r.used_amount||0),rem=b>0?Math.max(b-u,0):0,p=b>0?Math.min(u/b*100,100):0;return`<article class="campaign-card"><h3>${r.campaign_name||'ไม่ผูกแคมเปญ'}</h3><div class="meta"><span>งบ: ${b>0?money(b):'ไม่จำกัด'}</span><span>ใช้จริง: ${money(u)}</span><span>คงเหลือ: ${b>0?money(rem):'ไม่จำกัด'}</span><span>ใช้ทั้งหมด: ${Number(r.usage_count||0).toLocaleString('th-TH')} ครั้ง</span></div>${b>0?`<div class="budget-bar"><span style="width:${p.toFixed(2)}%"></span></div>`:''}</article>`}).join(''):'<div class="empty-state">ยังไม่มีข้อมูลแคมเปญ</div>'}
async function loadReport(){el.loadReportBtn.disabled=true;try{await Promise.all([loadSummary(),loadCampaigns()]);el.pageMessage.textContent=''}catch(e){console.error(e);el.pageMessage.textContent=e.message||'โหลดรายงานไม่สำเร็จ'}finally{el.loadReportBtn.disabled=false}}
async function init(){try{const g=await applyRoleGuard();if(!g)return;const{data:b,error}=await supabase.from('branches').select('id,name').eq('id',g.profile.branch_id).maybeSingle();if(error)throw error;el.branchText.textContent=`สาขา: ${b?.name||'-'}`;el.userName.textContent=g.profile.full_name||g.session.user.email||'ผู้ใช้งาน';setRange();await loadReport()}catch(e){el.pageMessage.textContent=e.message||'เปิด Cost Control ไม่สำเร็จ'}}
el.backBtn.onclick=()=>location.href='./dashboard.html';el.logoutBtn.onclick=async()=>{await supabase.auth.signOut();location.replace('./index.html')};el.loadReportBtn.onclick=loadReport;init()
