import { supabase } from './supabase.js'
import { applyRoleGuard } from './role-guard.js?v=3.12.0'

const $=id=>document.getElementById(id)
const el={
backBtn:$('backBtn'),logoutBtn:$('logoutBtn'),branchText:$('branchText'),userName:$('userName'),roleBadge:$('roleBadge'),
marketingBudgetTotal:$('marketingBudgetTotal'),marketingSpendTotal:$('marketingSpendTotal'),marketingBudgetRemaining:$('marketingBudgetRemaining'),activeCampaignCount:$('activeCampaignCount'),refreshMarketingBtn:$('refreshMarketingBtn'),
campaignId:$('campaignId'),campaignName:$('campaignName'),campaignBudget:$('campaignBudget'),campaignStopAtBudget:$('campaignStopAtBudget'),campaignStartsAt:$('campaignStartsAt'),campaignEndsAt:$('campaignEndsAt'),campaignActive:$('campaignActive'),campaignMessage:$('campaignMessage'),saveCampaignBtn:$('saveCampaignBtn'),resetCampaignBtn:$('resetCampaignBtn'),campaignList:$('campaignList'),
promotionId:$('promotionId'),promotionCampaign:$('promotionCampaign'),promotionName:$('promotionName'),discountType:$('discountType'),discountValue:$('discountValue'),minimumSubtotal:$('minimumSubtotal'),maximumDiscount:$('maximumDiscount'),startsAt:$('startsAt'),endsAt:$('endsAt'),promotionActive:$('promotionActive'),savePromotionBtn:$('savePromotionBtn'),resetFormBtn:$('resetFormBtn'),formMessage:$('formMessage'),promotionList:$('promotionList'),
couponId:$('couponId'),couponCampaign:$('couponCampaign'),couponType:$('couponType'),couponCode:$('couponCode'),generateCouponCodeBtn:$('generateCouponCodeBtn'),couponName:$('couponName'),couponDiscountType:$('couponDiscountType'),couponDiscountValue:$('couponDiscountValue'),couponMinimumSubtotal:$('couponMinimumSubtotal'),couponMaximumDiscount:$('couponMaximumDiscount'),couponStartsAt:$('couponStartsAt'),couponEndsAt:$('couponEndsAt'),couponActive:$('couponActive'),couponFormMessage:$('couponFormMessage'),saveCouponBtn:$('saveCouponBtn'),resetCouponFormBtn:$('resetCouponFormBtn'),couponList:$('couponList'),
approverSelect:$('approverSelect'),approverPin:$('approverPin'),saveApproverPinBtn:$('saveApproverPinBtn'),pinMessage:$('pinMessage'),marketingReportList:$('marketingReportList'),pageMessage:$('pageMessage')
}
const state={session:null,profile:null,role:'',branch:null,campaigns:[],promotions:[],coupons:[],approvers:[]}

const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')
const money=v=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',minimumFractionDigits:2}).format(Number(v||0))
function message(target,text='',ok=false){if(!target)return;target.textContent=text;target.style.color=ok?'#137333':'#b3261e'}
function toLocalInput(value){const d=value instanceof Date?value:new Date(value);if(Number.isNaN(d.getTime()))return'';const p=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
function formatDateTime(v){return v?new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'-'}
function statusOf(r){if(!r.is_active)return{code:'disabled',text:'ปิดใช้งาน'};const n=Date.now(),s=new Date(r.starts_at).getTime(),e=new Date(r.ends_at).getTime();if(n<s)return{code:'upcoming',text:'ยังไม่เริ่ม'};if(n>e)return{code:'expired',text:'หมดอายุ'};return{code:'active',text:'ใช้งานอยู่'}}
function setPair(a,b,days){const n=new Date();n.setSeconds(0,0);const e=new Date(n);e.setDate(e.getDate()+days);a.value=toLocalInput(n);b.value=toLocalInput(e)}
const isAdmin=()=>state.role==='admin'
function applyRoleUi(){document.querySelectorAll('.admin-only').forEach(n=>n.classList.toggle('hidden',!isAdmin()));if(!isAdmin()){const n=document.createElement('div');n.className='manager-note';n.textContent='โหมด Manager: ดูข้อมูล Marketing และงบประมาณได้ แต่สร้าง/แก้ไขได้เฉพาะ Admin';document.querySelector('.page')?.prepend(n)}}

function resetCampaign(){if(!isAdmin())return;el.campaignId.value='';el.campaignName.value='';el.campaignBudget.value='0';el.campaignStopAtBudget.checked=true;el.campaignActive.checked=true;setPair(el.campaignStartsAt,el.campaignEndsAt,30);el.saveCampaignBtn.textContent='บันทึกแคมเปญ';message(el.campaignMessage,'')}
function resetPromotion(){if(!isAdmin())return;el.promotionId.value='';el.promotionCampaign.value='';el.promotionName.value='';el.discountType.value='percent';el.discountValue.value='';el.minimumSubtotal.value='0';el.maximumDiscount.value='0';el.promotionActive.checked=true;setPair(el.startsAt,el.endsAt,7);el.savePromotionBtn.textContent='บันทึกโปรโมชั่น';message(el.formMessage,'')}
function resetCoupon(){if(!isAdmin())return;el.couponId.value='';el.couponCampaign.value='';el.couponType.value='coupon';el.couponCode.value='';el.couponName.value='';el.couponDiscountType.value='amount';el.couponDiscountValue.value='';el.couponMinimumSubtotal.value='0';el.couponMaximumDiscount.value='0';el.couponActive.checked=true;setPair(el.couponStartsAt,el.couponEndsAt,30);el.saveCouponBtn.textContent='บันทึกคูปอง / วอชเชอร์';message(el.couponFormMessage,'')}

function renderCampaignSelects(){const opts='<option value="">ไม่ผูกแคมเปญ</option>'+state.campaigns.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');el.promotionCampaign.innerHTML=opts;el.couponCampaign.innerHTML=opts}
async function loadCampaigns(){const{data,error}=await supabase.rpc('marketing_list_campaigns');if(error)throw error;state.campaigns=Array.isArray(data)?data:[];renderCampaignSelects();renderCampaigns()}
function renderCampaigns(){if(!state.campaigns.length){el.campaignList.innerHTML='<div class="empty-state">ยังไม่มีแคมเปญ</div>';return}el.campaignList.innerHTML=state.campaigns.map(c=>{const st=statusOf(c),b=Number(c.budget_amount||0),u=Number(c.used_amount||0),rem=b>0?Math.max(b-u,0):0,pct=b>0?Math.min(u/b*100,100):0;return`<article class="item-card"><div><h3>${esc(c.name)}</h3><span class="status-pill ${st.code}">${st.text}</span><div class="meta"><span>งบ: ${b>0?money(b):'ไม่จำกัด'}</span><span>ใช้จริง: ${money(u)}</span><span>คงเหลือ: ${b>0?money(rem):'ไม่จำกัด'}</span><span>${formatDateTime(c.starts_at)} → ${formatDateTime(c.ends_at)}</span><span>${c.stop_when_budget_reached?'หยุดอัตโนมัติเมื่อใช้งบครบ':'ไม่หยุดอัตโนมัติเมื่อแตะงบ'}</span></div>${b>0?`<div class="budget-bar"><span style="width:${pct.toFixed(2)}%"></span></div>`:''}</div>${isAdmin()?`<div class="card-actions"><button class="outline-btn" data-edit-campaign="${esc(c.id)}">แก้ไข</button><button class="outline-btn" data-toggle-campaign="${esc(c.id)}">${c.is_active?'ปิด':'เปิด'}</button></div>`:''}</article>`}).join('')}
async function saveCampaign(){if(!isAdmin())return;const name=el.campaignName.value.trim(),budget=Math.max(Number(el.campaignBudget.value||0),0),s=new Date(el.campaignStartsAt.value),e=new Date(el.campaignEndsAt.value);if(!name)return message(el.campaignMessage,'กรุณาระบุชื่อแคมเปญ');if(Number.isNaN(s.getTime())||Number.isNaN(e.getTime())||e<=s)return message(el.campaignMessage,'กรุณาตรวจสอบวันเวลา');el.saveCampaignBtn.disabled=true;try{const{error}=await supabase.rpc('admin_save_marketing_campaign',{p_campaign_id:el.campaignId.value||null,p_name:name,p_budget_amount:budget,p_stop_when_budget_reached:el.campaignStopAtBudget.checked,p_starts_at:s.toISOString(),p_ends_at:e.toISOString(),p_is_active:el.campaignActive.checked});if(error)throw error;message(el.campaignMessage,'บันทึกแคมเปญสำเร็จ',true);resetCampaign();await refreshAll()}catch(e){message(el.campaignMessage,e.message||'บันทึกไม่สำเร็จ')}finally{el.saveCampaignBtn.disabled=false}}
function editCampaign(id){const c=state.campaigns.find(x=>x.id===id);if(!c||!isAdmin())return;el.campaignId.value=c.id;el.campaignName.value=c.name;el.campaignBudget.value=Number(c.budget_amount||0);el.campaignStopAtBudget.checked=c.stop_when_budget_reached!==false;el.campaignStartsAt.value=toLocalInput(c.starts_at);el.campaignEndsAt.value=toLocalInput(c.ends_at);el.campaignActive.checked=c.is_active!==false;el.saveCampaignBtn.textContent='บันทึกการแก้ไขแคมเปญ';window.scrollTo({top:0,behavior:'smooth'})}
async function toggleCampaign(id){const c=state.campaigns.find(x=>x.id===id);if(!c||!isAdmin())return;const{error}=await supabase.rpc('admin_set_marketing_campaign_active',{p_campaign_id:id,p_is_active:!c.is_active});if(error)throw error;await refreshAll()}

async function loadPromotions(){const{data,error}=await supabase.rpc('admin_list_promotions');if(error)throw error;state.promotions=Array.isArray(data)?data:[];renderPromotions()}
function renderPromotions(){if(!state.promotions.length){el.promotionList.innerHTML='<div class="empty-state">ยังไม่มีโปรโมชั่น</div>';return}el.promotionList.innerHTML=state.promotions.map(p=>{const st=statusOf(p),d=p.discount_type==='percent'?`${Number(p.discount_value)}%`:money(p.discount_value);return`<article class="item-card"><div><h3>${esc(p.name)}</h3><span class="status-pill ${st.code}">${st.text}</span><div class="meta"><span>ส่วนลด: ${d}</span><span>แคมเปญ: ${esc(p.campaign_name||'ไม่ผูกแคมเปญ')}</span><span>ขั้นต่ำ: ${money(p.minimum_subtotal)}</span><span>${formatDateTime(p.starts_at)} → ${formatDateTime(p.ends_at)}</span><span>สร้างโดย: ${esc(p.created_by_name||'-')}</span></div></div>${isAdmin()?`<div class="card-actions"><button class="outline-btn" data-edit-promotion="${esc(p.id)}">แก้ไข</button><button class="outline-btn" data-toggle-promotion="${esc(p.id)}">${p.is_active?'ปิด':'เปิด'}</button></div>`:''}</article>`}).join('')}
async function savePromotion(){if(!isAdmin())return;const name=el.promotionName.value.trim(),v=Number(el.discountValue.value||0),s=new Date(el.startsAt.value),e=new Date(el.endsAt.value);if(!name)return message(el.formMessage,'กรุณาระบุชื่อโปรโมชั่น');if(v<=0)return message(el.formMessage,'มูลค่าส่วนลดต้องมากกว่า 0');if(el.discountType.value==='percent'&&v>100)return message(el.formMessage,'เปอร์เซ็นต์ต้องไม่เกิน 100%');if(Number.isNaN(s.getTime())||Number.isNaN(e.getTime())||e<=s)return message(el.formMessage,'กรุณาตรวจสอบวันเวลา');try{const{error}=await supabase.rpc('admin_save_promotion',{p_promotion_id:el.promotionId.value||null,p_campaign_id:el.promotionCampaign.value||null,p_name:name,p_discount_type:el.discountType.value,p_discount_value:v,p_minimum_subtotal:Math.max(Number(el.minimumSubtotal.value||0),0),p_maximum_discount:Math.max(Number(el.maximumDiscount.value||0),0),p_starts_at:s.toISOString(),p_ends_at:e.toISOString(),p_is_active:el.promotionActive.checked});if(error)throw error;message(el.formMessage,'บันทึกโปรโมชั่นสำเร็จ',true);resetPromotion();await refreshAll()}catch(e){message(el.formMessage,e.message||'บันทึกโปรโมชั่นไม่สำเร็จ')}}
function editPromotion(id){const p=state.promotions.find(x=>x.id===id);if(!p||!isAdmin())return;el.promotionId.value=p.id;el.promotionCampaign.value=p.campaign_id||'';el.promotionName.value=p.name;el.discountType.value=p.discount_type;el.discountValue.value=Number(p.discount_value||0);el.minimumSubtotal.value=Number(p.minimum_subtotal||0);el.maximumDiscount.value=Number(p.maximum_discount||0);el.startsAt.value=toLocalInput(p.starts_at);el.endsAt.value=toLocalInput(p.ends_at);el.promotionActive.checked=p.is_active!==false;el.savePromotionBtn.textContent='บันทึกการแก้ไขโปรโมชั่น'}
async function togglePromotion(id){const p=state.promotions.find(x=>x.id===id);if(!p||!isAdmin())return;const{error}=await supabase.rpc('admin_set_promotion_active',{p_promotion_id:id,p_is_active:!p.is_active});if(error)throw error;await refreshAll()}

function randomCode(){const c='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';for(let i=0;i<8;i++)s+=c[Math.floor(Math.random()*c.length)];return s}
async function loadCoupons(){const{data,error}=await supabase.rpc('admin_list_coupons');if(error)throw error;state.coupons=Array.isArray(data)?data:[];renderCoupons()}
function renderCoupons(){if(!state.coupons.length){el.couponList.innerHTML='<div class="empty-state">ยังไม่มีคูปอง / วอชเชอร์</div>';return}el.couponList.innerHTML=state.coupons.map(c=>{const st=statusOf(c),d=c.discount_type==='percent'?`${Number(c.discount_value)}%`:money(c.discount_value);return`<article class="item-card"><div><h3>${c.coupon_type==='voucher'?'🎫':'🎟️'} ${esc(c.name)}</h3><div class="code-badge">${esc(c.code)}</div><span class="status-pill ${st.code}">${st.text}</span><div class="meta"><span>ส่วนลด: ${d}</span><span>แคมเปญ: ${esc(c.campaign_name||'ไม่ผูกแคมเปญ')}</span><span>ขั้นต่ำ: ${money(c.minimum_subtotal)}</span><span>${formatDateTime(c.starts_at)} → ${formatDateTime(c.ends_at)}</span><span>สร้างโดย: ${esc(c.created_by_name||'-')}</span></div></div>${isAdmin()?`<div class="card-actions"><button class="outline-btn" data-edit-coupon="${esc(c.id)}">แก้ไข</button><button class="outline-btn" data-toggle-coupon="${esc(c.id)}">${c.is_active?'ปิด':'เปิด'}</button></div>`:''}</article>`}).join('')}
async function saveCoupon(){if(!isAdmin())return;const code=el.couponCode.value.trim().toUpperCase(),name=el.couponName.value.trim(),v=Number(el.couponDiscountValue.value||0),s=new Date(el.couponStartsAt.value),e=new Date(el.couponEndsAt.value);if(!/^[A-Z0-9_-]{4,40}$/.test(code))return message(el.couponFormMessage,'รหัสต้องมี 4-40 ตัว ใช้ A-Z,0-9,_,-');if(!name)return message(el.couponFormMessage,'กรุณาระบุชื่อ');if(v<=0)return message(el.couponFormMessage,'มูลค่าส่วนลดต้องมากกว่า 0');if(el.couponDiscountType.value==='percent'&&v>100)return message(el.couponFormMessage,'เปอร์เซ็นต์ต้องไม่เกิน 100%');if(Number.isNaN(s.getTime())||Number.isNaN(e.getTime())||e<=s)return message(el.couponFormMessage,'กรุณาตรวจสอบวันเวลา');try{const{error}=await supabase.rpc('admin_save_coupon',{p_coupon_id:el.couponId.value||null,p_campaign_id:el.couponCampaign.value||null,p_coupon_type:el.couponType.value,p_code:code,p_name:name,p_discount_type:el.couponDiscountType.value,p_discount_value:v,p_minimum_subtotal:Math.max(Number(el.couponMinimumSubtotal.value||0),0),p_maximum_discount:Math.max(Number(el.couponMaximumDiscount.value||0),0),p_starts_at:s.toISOString(),p_ends_at:e.toISOString(),p_is_active:el.couponActive.checked});if(error)throw error;message(el.couponFormMessage,'บันทึกคูปอง / วอชเชอร์สำเร็จ',true);resetCoupon();await refreshAll()}catch(e){message(el.couponFormMessage,e.message?.includes('COUPON_CODE_EXISTS')?'รหัสนี้มีอยู่แล้ว':e.message||'บันทึกไม่สำเร็จ')}}
function editCoupon(id){const c=state.coupons.find(x=>x.id===id);if(!c||!isAdmin())return;el.couponId.value=c.id;el.couponCampaign.value=c.campaign_id||'';el.couponType.value=c.coupon_type;el.couponCode.value=c.code;el.couponName.value=c.name;el.couponDiscountType.value=c.discount_type;el.couponDiscountValue.value=Number(c.discount_value||0);el.couponMinimumSubtotal.value=Number(c.minimum_subtotal||0);el.couponMaximumDiscount.value=Number(c.maximum_discount||0);el.couponStartsAt.value=toLocalInput(c.starts_at);el.couponEndsAt.value=toLocalInput(c.ends_at);el.couponActive.checked=c.is_active!==false;el.saveCouponBtn.textContent='บันทึกการแก้ไขคูปอง'}
async function toggleCoupon(id){const c=state.coupons.find(x=>x.id===id);if(!c||!isAdmin())return;const{error}=await supabase.rpc('admin_set_coupon_active',{p_coupon_id:id,p_is_active:!c.is_active});if(error)throw error;await refreshAll()}

async function loadApprovers(){if(!isAdmin())return;const{data,error}=await supabase.rpc('admin_list_discount_approvers');if(error)throw error;state.approvers=Array.isArray(data)?data:[];el.approverSelect.innerHTML=state.approvers.map(p=>`<option value="${esc(p.id)}">${esc(p.full_name||p.id)} • ${p.role==='admin'?'Admin':'Manager'} ${p.has_pin?'• มี PIN แล้ว':'• ยังไม่มี PIN'}</option>`).join('')}
async function savePin(){if(!isAdmin())return;const id=el.approverSelect.value,pin=el.approverPin.value.trim();if(!id)return message(el.pinMessage,'กรุณาเลือกผู้อนุมัติ');if(!/^\d{6}$/.test(pin))return message(el.pinMessage,'PIN ต้องเป็นตัวเลข 6 หลัก');try{const{error}=await supabase.rpc('admin_set_discount_approval_pin',{p_user_id:id,p_pin:pin});if(error)throw error;el.approverPin.value='';message(el.pinMessage,'บันทึก PIN สำเร็จ',true);await loadApprovers()}catch(e){message(el.pinMessage,e.message||'บันทึก PIN ไม่สำเร็จ')}}

async function loadSummary(){const{data,error}=await supabase.rpc('marketing_summary');if(error)throw error;const r=Array.isArray(data)?data[0]:data;el.marketingBudgetTotal.textContent=money(r?.budget_total||0);el.marketingSpendTotal.textContent=money(r?.marketing_spend||0);el.marketingBudgetRemaining.textContent=money(r?.budget_remaining||0);el.activeCampaignCount.textContent=Number(r?.active_campaign_count||0).toLocaleString('th-TH')}
async function loadReport(){const{data,error}=await supabase.rpc('marketing_campaign_report');if(error)throw error;const a=Array.isArray(data)?data:[];el.marketingReportList.innerHTML=a.length?a.map(r=>{const b=Number(r.budget_amount||0),u=Number(r.used_amount||0),rem=b>0?Math.max(b-u,0):0;return`<article class="item-card"><div><h3>${esc(r.campaign_name||'ไม่ผูกแคมเปญ')}</h3><div class="meta"><span>งบ: ${b>0?money(b):'ไม่จำกัด'}</span><span>ใช้ไป: ${money(u)}</span><span>คงเหลือ: ${b>0?money(rem):'ไม่จำกัด'}</span><span>ใช้ทั้งหมด: ${Number(r.usage_count||0).toLocaleString('th-TH')} ครั้ง</span><span>โปรโมชั่น: ${Number(r.promotion_usage_count||0).toLocaleString('th-TH')} ครั้ง</span><span>คูปอง/Voucher: ${Number(r.coupon_usage_count||0).toLocaleString('th-TH')} ครั้ง</span></div></div></article>`}).join(''):'<div class="empty-state">ยังไม่มีข้อมูลการใช้ Marketing</div>'}
async function refreshAll(){const jobs=[loadCampaigns(),loadPromotions(),loadCoupons(),loadSummary(),loadReport()];if(isAdmin())jobs.push(loadApprovers());await Promise.all(jobs)}

async function init(){try{const g=await applyRoleGuard();if(!g)return;state.session=g.session;state.profile=g.profile;state.role=String(g.role||'').toLowerCase();const{data:b,error}=await supabase.from('branches').select('id,name').eq('id',state.profile.branch_id).maybeSingle();if(error)throw error;state.branch=b;el.branchText.textContent=`สาขา: ${b?.name||'-'}`;el.userName.textContent=state.profile.full_name||state.session.user.email||'ผู้ใช้งาน';el.roleBadge.textContent=isAdmin()?'Admin':'Manager';applyRoleUi();if(isAdmin()){resetCampaign();resetPromotion();resetCoupon()}await refreshAll()}catch(e){console.error(e);message(el.pageMessage,e.message||'เปิด Marketing ไม่สำเร็จ')}}

el.backBtn.onclick=()=>location.href='./dashboard.html'
el.logoutBtn.onclick=async()=>{await supabase.auth.signOut();location.replace('./index.html')}
el.refreshMarketingBtn.onclick=refreshAll
el.resetCampaignBtn.onclick=resetCampaign;el.saveCampaignBtn.onclick=saveCampaign
el.resetFormBtn.onclick=resetPromotion;el.savePromotionBtn.onclick=savePromotion
el.resetCouponFormBtn.onclick=resetCoupon;el.saveCouponBtn.onclick=saveCoupon
el.generateCouponCodeBtn.onclick=()=>el.couponCode.value=randomCode()
el.saveApproverPinBtn.onclick=savePin

el.campaignList.onclick=async e=>{const a=e.target.closest('[data-edit-campaign]');if(a)return editCampaign(a.dataset.editCampaign);const t=e.target.closest('[data-toggle-campaign]');if(t)try{await toggleCampaign(t.dataset.toggleCampaign)}catch(x){message(el.pageMessage,x.message)}}
el.promotionList.onclick=async e=>{const a=e.target.closest('[data-edit-promotion]');if(a)return editPromotion(a.dataset.editPromotion);const t=e.target.closest('[data-toggle-promotion]');if(t)try{await togglePromotion(t.dataset.togglePromotion)}catch(x){message(el.pageMessage,x.message)}}
el.couponList.onclick=async e=>{const a=e.target.closest('[data-edit-coupon]');if(a)return editCoupon(a.dataset.editCoupon);const t=e.target.closest('[data-toggle-coupon]');if(t)try{await toggleCoupon(t.dataset.toggleCoupon)}catch(x){message(el.pageMessage,x.message)}}

init()
