import { supabase } from './supabase.js'
import { applyRoleGuard } from './role-guard.js?v=3.12.0'

const $=id=>document.getElementById(id)
const el={backBtn:$('backBtn'),refreshBtn:$('refreshBtn'),branchText:$('branchText'),dateFrom:$('dateFrom'),dateTo:$('dateTo'),searchInput:$('searchInput'),statusFilter:$('statusFilter'),searchBtn:$('searchBtn'),orderCount:$('orderCount'),payableTotal:$('payableTotal'),cancelledTotal:$('cancelledTotal'),pageMessage:$('pageMessage'),orderList:$('orderList'),emptyState:$('emptyState')}
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'","&#039;")
const money=v=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB'}).format(Number(v||0))
const dt=v=>v?new Intl.DateTimeFormat('th-TH',{dateStyle:'short',timeStyle:'medium'}).format(new Date(v)):'-'
function localDate(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function orderName(o){if(o.order_type==='takeaway')return o.queue_no?`กลับบ้าน • คิว ${String(o.queue_no).padStart(3,'0')}`:'กลับบ้าน';return o.table_name||(o.table_no?`โต๊ะ ${o.table_no}`:'ไม่ระบุโต๊ะ')}
function statusText(v){return ({pending:'รอรับออเดอร์',preparing:'กำลังทำ',ready:'พร้อมเสิร์ฟ',served:'เสิร์ฟแล้ว',cancelled:'ยกเลิก'}[v]||v||'-')}
function orderStatus(v){return ({open:'เปิดอยู่',paid:'ชำระแล้ว',closed:'ปิดแล้ว',cancelled:'ยกเลิก'}[v]||v||'-')}
function modifierText(v){if(!v)return '';try{const a=typeof v==='string'?JSON.parse(v):v;if(Array.isArray(a))return a.map(x=>x?.name||x?.label||x?.option_name||'').filter(Boolean).join(', ')}catch{}return ''}
function timeline(i){const p=[`รับออเดอร์: ${dt(i.created_at)}`];if(i.kitchen_started_at)p.push(`เริ่มทำ: ${dt(i.kitchen_started_at)}`);if(i.kitchen_ready_at)p.push(`พร้อม: ${dt(i.kitchen_ready_at)}`);if(i.kitchen_served_at)p.push(`เสิร์ฟ: ${dt(i.kitchen_served_at)}`);return p.map(x=>`<div>${esc(x)}</div>`).join('')}
function groupRounds(items){const m=new Map();for(const i of items||[]){const n=Number(i.round_no||1);if(!m.has(n))m.set(n,[]);m.get(n).push(i)}return [...m.entries()].sort((a,b)=>a[0]-b[0])}
function renderOrder(o){const rounds=groupRounds(o.items);return `<article class="card order-card"><div class="order-head"><div class="order-title"><h2>${esc(orderName(o))}</h2><small>${esc(dt(o.opened_at))} • ${esc(o.order_id)}</small><br><span class="status-pill">${esc(orderStatus(o.status))}</span></div><div class="order-summary"><strong>${money(o.payable_amount)}</strong><small>${Number(o.total_lines||0)} รายการ • ยกเลิก ${Number(o.cancelled_lines||0)}</small></div></div>${rounds.map(([round,items])=>`<section class="round"><div class="round-head"><strong>${round===1?'รอบสั่งแรก':`🆕 สั่งเพิ่ม รอบ ${round}`}</strong><span>${esc(dt(items[0]?.created_at))}</span></div>${items.map(i=>{const mods=modifierText(i.modifiers),cancelled=i.item_status==='cancelled';return `<div class="item"><div class="item-name"><strong>${esc(i.product_name)} ×${Number(i.quantity||0).toLocaleString('th-TH')}</strong><small>${money(i.unit_price)}${mods?` • ${esc(mods)}`:''}${i.item_note?` • ${esc(i.item_note)}`:''}</small>${cancelled?`<div class="cancel-box">เหตุผล: ${esc(i.cancel_reason||'-')}<br>ผู้ยกเลิก: ${esc(i.cancelled_by_name||'-')} • ${esc(dt(i.cancelled_at))}</div>`:''}</div><div class="item-status ${esc(i.item_status)}">${esc(statusText(i.item_status))}</div><strong>${money(i.total_price)}</strong><div class="timeline">${timeline(i)}</div></div>`}).join('')}</section>`).join('')}</article>`}
function render(data){const s=data?.summary||{},orders=data?.orders||[];el.orderCount.textContent=Number(s.orders||0).toLocaleString('th-TH');el.payableTotal.textContent=money(s.payable_amount);el.cancelledTotal.textContent=money(s.cancelled_amount);el.orderList.innerHTML=orders.map(renderOrder).join('');el.emptyState.classList.toggle('hidden',orders.length>0)}
async function loadHistory(){el.searchBtn.disabled=true;el.refreshBtn.disabled=true;el.pageMessage.textContent='กำลังโหลด...';try{const{data,error}=await supabase.rpc('get_restaurant_order_history',{p_date_from:el.dateFrom.value,p_date_to:el.dateTo.value,p_keyword:el.searchInput.value.trim()||null,p_status:el.statusFilter.value||null});if(error)throw error;render(data);el.pageMessage.textContent=''}catch(e){console.error(e);el.pageMessage.textContent=e.message||'โหลดประวัติออเดอร์ไม่สำเร็จ'}finally{el.searchBtn.disabled=false;el.refreshBtn.disabled=false}}
async function init(){try{const guard=await applyRoleGuard();if(!guard)return;if(!['admin','manager'].includes(guard.role)){location.replace('./pos.html');return}const{data,error}=await supabase.from('branches').select('id,name').eq('id',guard.profile.branch_id).maybeSingle();if(error)throw error;el.branchText.textContent=`สาขา: ${data?.name||'-'}`;const today=localDate(new Date());el.dateFrom.value=today;el.dateTo.value=today;await loadHistory()}catch(e){console.error(e);el.pageMessage.textContent=e.message||'เปิดหน้าประวัติออเดอร์ไม่สำเร็จ'}}
el.backBtn?.addEventListener('click',()=>location.href='./dashboard.html')
el.refreshBtn?.addEventListener('click',loadHistory)
el.searchBtn?.addEventListener('click',loadHistory)
el.searchInput?.addEventListener('keydown',e=>{if(e.key==='Enter')loadHistory()})
init()
