import { supabase } from './supabase.js'

const state={session:null,profile:null,branch:null,tables:[],editingTable:null,qrTable:null}
const $=id=>document.getElementById(id)
const el={backBtn:$('backBtn'),refreshBtn:$('refreshBtn'),addTableBtn:$('addTableBtn'),branchText:$('branchText'),userName:$('userName'),searchInput:$('searchInput'),statusFilter:$('statusFilter'),loading:$('loading'),empty:$('empty'),tableGrid:$('tableGrid'),pageMessage:$('pageMessage'),totalTablesText:$('totalTablesText'),availableTablesText:$('availableTablesText'),occupiedTablesText:$('occupiedTablesText'),inactiveTablesText:$('inactiveTablesText'),tableModal:$('tableModal'),tableModalTitle:$('tableModalTitle'),tableModalSubtitle:$('tableModalSubtitle'),closeTableModalBtn:$('closeTableModalBtn'),tableForm:$('tableForm'),editingTableId:$('editingTableId'),tableNoInput:$('tableNoInput'),tableNameInput:$('tableNameInput'),capacityInput:$('capacityInput'),statusInput:$('statusInput'),isActiveInput:$('isActiveInput'),tableFormMessage:$('tableFormMessage'),cancelTableBtn:$('cancelTableBtn'),saveTableBtn:$('saveTableBtn'),qrModal:$('qrModal'),qrTableName:$('qrTableName'),tableQr:$('tableQr'),qrTokenText:$('qrTokenText'),closeQrModalBtn:$('closeQrModalBtn'),printQrBtn:$('printQrBtn')}
function msg(target,text=''){if(target)target.textContent=text}
function esc(value){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function normalizeStatus(status){return String(status||'available').trim().toLowerCase()}
function statusText(status){return({available:'ว่าง',occupied:'มีลูกค้า',reserved:'จอง',disabled:'ปิดใช้งาน'}[normalizeStatus(status)]||status)}
function statusClass(status){const v=normalizeStatus(status);return ['available','occupied','reserved','disabled'].includes(v)?`status-${v}`:'status-disabled'}

async function requireSession(){const{data:{session},error}=await supabase.auth.getSession();if(error)throw error;if(!session){location.replace('./index.html');return null}state.session=session;return session}
async function loadProfile(userId){const{data,error}=await supabase.from('profiles').select('id,full_name,role,branch_id').eq('id',userId).maybeSingle();if(error)throw error;if(!data?.branch_id)throw new Error('บัญชียังไม่ได้กำหนดสาขา');const role=String(data.role||'').trim().toLowerCase();if(!['admin','manager','staff'].includes(role))throw new Error('บัญชีนี้ไม่มีสิทธิ์จัดการโต๊ะ');state.profile=data}
async function loadBranch(){const{data,error}=await supabase.from('branches').select('id,name').eq('id',state.profile.branch_id).maybeSingle();if(error)throw error;if(!data)throw new Error('ไม่พบสาขา');state.branch=data}
function renderUser(){el.userName.textContent=state.profile.full_name||state.session.user.email.split('@')[0];el.branchText.textContent=`สาขา: ${state.branch.name}`}

async function loadTables(){el.loading.classList.remove('hidden');el.empty.classList.add('hidden');el.tableGrid.classList.add('hidden');msg(el.pageMessage,'');try{const{data,error}=await supabase.from('restaurant_tables').select('id,branch_id,table_no,table_name,capacity,status,qr_token,is_active,updated_at').eq('branch_id',state.profile.branch_id).order('table_no',{ascending:true});if(error)throw error;state.tables=data||[];renderSummary();renderTables()}catch(error){console.error('Load tables error:',error);msg(el.pageMessage,error.message||'โหลดข้อมูลโต๊ะไม่สำเร็จ')}finally{el.loading.classList.add('hidden')}}
function renderSummary(){el.totalTablesText.textContent=state.tables.length.toLocaleString('th-TH');el.availableTablesText.textContent=state.tables.filter(t=>t.is_active&&normalizeStatus(t.status)==='available').length.toLocaleString('th-TH');el.occupiedTablesText.textContent=state.tables.filter(t=>t.is_active&&normalizeStatus(t.status)==='occupied').length.toLocaleString('th-TH');el.inactiveTablesText.textContent=state.tables.filter(t=>!t.is_active||normalizeStatus(t.status)==='disabled').length.toLocaleString('th-TH')}
function filteredTables(){const keyword=el.searchInput.value.trim().toLowerCase();const status=el.statusFilter.value;return state.tables.filter(table=>{const s=[table.table_no,table.table_name].filter(v=>v!==null&&v!==undefined).join(' ').toLowerCase();const searchMatch=!keyword||s.includes(keyword);const statusMatch=!status||(status==='disabled'?(!table.is_active||normalizeStatus(table.status)==='disabled'):normalizeStatus(table.status)===status);return searchMatch&&statusMatch})}
function renderTables(){const list=filteredTables();if(!list.length){el.empty.classList.remove('hidden');el.tableGrid.classList.add('hidden');return}el.empty.classList.add('hidden');el.tableGrid.classList.remove('hidden');el.tableGrid.innerHTML=list.map(table=>{const status=table.is_active?normalizeStatus(table.status):'disabled';const occupied=status==='occupied';return `<article class="table-card ${table.is_active?'':'inactive'}"><div class="table-card-head"><div><h3>${esc(table.table_name||`โต๊ะ ${table.table_no}`)}</h3><span class="table-no">โต๊ะหมายเลข ${esc(table.table_no)}</span></div><span class="status-badge ${statusClass(status)}">${esc(statusText(status))}</span></div><div class="table-meta"><div>👥 ${Number(table.capacity||0).toLocaleString('th-TH')} ที่นั่ง</div><div>${table.is_active?'✅ เปิดใช้งาน':'⛔ ปิดใช้งาน'}</div><div>QR: ${table.qr_token?'พร้อม':'ยังไม่มี'}</div></div><div class="table-actions"><button type="button" data-act="edit" data-id="${esc(table.id)}" ${occupied?'disabled':''}>✏️ แก้ไข</button><button type="button" data-act="qr" data-id="${esc(table.id)}">▣ QR โต๊ะ</button></div></article>`}).join('')}

function openAddTableModal(){state.editingTable=null;el.editingTableId.value='';el.tableModalTitle.textContent='เพิ่มโต๊ะ';el.tableModalSubtitle.textContent='สร้างโต๊ะใหม่ในสาขานี้';const nextNo=state.tables.reduce((max,t)=>Math.max(max,Number(t.table_no||0)),0)+1;el.tableNoInput.value=String(nextNo);el.tableNameInput.value=`โต๊ะ ${nextNo}`;el.capacityInput.value='4';el.statusInput.value='available';el.isActiveInput.checked=true;msg(el.tableFormMessage,'');el.tableModal.classList.remove('hidden')}
function openEditTableModal(tableId){const table=state.tables.find(i=>i.id===tableId);if(!table)return;if(normalizeStatus(table.status)==='occupied'){msg(el.pageMessage,'โต๊ะนี้มีลูกค้าอยู่ ไม่สามารถแก้ไขได้จนกว่าจะปิดบิล');return}state.editingTable=table;el.editingTableId.value=table.id;el.tableModalTitle.textContent='แก้ไขโต๊ะ';el.tableModalSubtitle.textContent=table.table_name||`โต๊ะ ${table.table_no}`;el.tableNoInput.value=String(table.table_no);el.tableNameInput.value=table.table_name||`โต๊ะ ${table.table_no}`;el.capacityInput.value=String(table.capacity||1);const s=normalizeStatus(table.status);el.statusInput.value=['available','reserved','disabled'].includes(s)?s:'available';el.isActiveInput.checked=Boolean(table.is_active);msg(el.tableFormMessage,'');el.tableModal.classList.remove('hidden')}
function closeTableModal(){el.tableModal.classList.add('hidden');state.editingTable=null;msg(el.tableFormMessage,'')}
async function saveTable(event){event.preventDefault();const tableNo=Number(el.tableNoInput.value);const tableName=el.tableNameInput.value.trim();const capacity=Number(el.capacityInput.value);let status=normalizeStatus(el.statusInput.value);const isActive=Boolean(el.isActiveInput.checked);if(!Number.isInteger(tableNo)||tableNo<1){msg(el.tableFormMessage,'เลขโต๊ะไม่ถูกต้อง');return}if(!tableName){msg(el.tableFormMessage,'กรุณากรอกชื่อโต๊ะ');return}if(!Number.isInteger(capacity)||capacity<1){msg(el.tableFormMessage,'จำนวนที่นั่งไม่ถูกต้อง');return}if(!isActive)status='disabled';const duplicate=state.tables.some(t=>Number(t.table_no)===tableNo&&t.id!==state.editingTable?.id);if(duplicate){msg(el.tableFormMessage,`มีโต๊ะหมายเลข ${tableNo} อยู่แล้ว`);return}el.saveTableBtn.disabled=true;el.saveTableBtn.textContent='กำลังบันทึก...';msg(el.tableFormMessage,'');try{if(state.editingTable){const{error}=await supabase.from('restaurant_tables').update({table_no:tableNo,table_name:tableName,capacity,status,is_active:isActive}).eq('id',state.editingTable.id).eq('branch_id',state.profile.branch_id);if(error)throw error}else{const payload={branch_id:state.profile.branch_id,table_no:tableNo,table_name:tableName,capacity,status,is_active:isActive};if(crypto.randomUUID)payload.qr_token=crypto.randomUUID();const{error}=await supabase.from('restaurant_tables').insert(payload);if(error)throw error}closeTableModal();await loadTables();msg(el.pageMessage,'บันทึกข้อมูลโต๊ะเรียบร้อย');setTimeout(()=>{if(el.pageMessage.textContent==='บันทึกข้อมูลโต๊ะเรียบร้อย')msg(el.pageMessage,'')},1500)}catch(error){console.error('Save table error:',error);let m=error.message||'บันทึกข้อมูลโต๊ะไม่สำเร็จ';if(m.toLowerCase().includes('duplicate'))m='เลขโต๊ะหรือข้อมูลโต๊ะซ้ำกับข้อมูลที่มีอยู่';msg(el.tableFormMessage,m)}finally{el.saveTableBtn.disabled=false;el.saveTableBtn.textContent='บันทึก'}}

function closeQrModal(){el.qrModal.classList.add('hidden');state.qrTable=null}
function openQrModal(tableId){const table=state.tables.find(i=>i.id===tableId);if(!table)return;if(!table.qr_token){msg(el.pageMessage,'โต๊ะนี้ยังไม่มี QR Token');return}state.qrTable=table;el.qrTableName.textContent=table.table_name||`โต๊ะ ${table.table_no}`;el.qrTokenText.textContent=table.qr_token;el.tableQr.innerHTML='';try{if(!window.QRCode)throw new Error('ไม่พบ QRCode library');const qrUrl=new URL('./customer-order.html',window.location.href);qrUrl.searchParams.set('token',table.qr_token);new window.QRCode(el.tableQr,{text:qrUrl.href,width:220,height:220,correctLevel:window.QRCode.CorrectLevel.M})}catch(error){console.error('Table QR error:',error);el.tableQr.textContent=error.message||'สร้าง QR ไม่สำเร็จ'}el.qrModal.classList.remove('hidden')}

async function init(){try{const session=await requireSession();if(!session)return;await loadProfile(session.user.id);await loadBranch();renderUser();await loadTables()}catch(error){console.error('Tables init error:',error);msg(el.pageMessage,error.message||'โหลดหน้าจัดการโต๊ะไม่สำเร็จ');el.loading?.classList.add('hidden')}}

el.backBtn?.addEventListener('click',()=>{location.href='./dashboard.html'})
el.refreshBtn?.addEventListener('click',loadTables)
el.addTableBtn?.addEventListener('click',openAddTableModal)
el.searchInput?.addEventListener('input',renderTables)
el.statusFilter?.addEventListener('change',renderTables)
el.tableGrid?.addEventListener('click',event=>{const button=event.target.closest('[data-act]');if(!button)return;const action=button.dataset.act;const tableId=button.dataset.id;if(action==='edit'){openEditTableModal(tableId);return}if(action==='qr')openQrModal(tableId)})
el.tableForm?.addEventListener('submit',saveTable)
el.closeTableModalBtn?.addEventListener('click',closeTableModal)
el.cancelTableBtn?.addEventListener('click',closeTableModal)
el.closeQrModalBtn?.addEventListener('click',closeQrModal)
el.printQrBtn?.addEventListener('click',()=>{if(state.qrTable)window.print()})
el.tableModal?.addEventListener('click',event=>{if(event.target===el.tableModal)closeTableModal()})
el.qrModal?.addEventListener('click',event=>{if(event.target===el.qrModal)closeQrModal()})
document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;if(el.qrModal&&!el.qrModal.classList.contains('hidden')){closeQrModal();return}if(el.tableModal&&!el.tableModal.classList.contains('hidden'))closeTableModal()})
supabase.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||!session)location.replace('./index.html')})
init()
